<?
$_ETC_ADDED1="브랜드";
$_ETC_ADDED2="원산지";
$_ETC_ADDED3="출시일";
$_ETC_ADDED4="이동통신사";
$_ETC_ADDED5="";
$_ETC_ADDED6="";
$_ETC_ADDED7="";
$_ETC_ADDED8="";
$_ETC_ADDED9="";
$_ETC_ADDED10="";
?>